- name: Install and configure MongoDB
  hosts: mongodb
  become: yes

  tasks:
    - name: Copy MongoDB repo to yum.repos.d
      copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDB
      yum:
        name: mongodb-org
        state: present

    - name: Enable remote connections to MongoDB
      replace:
        path: /etc/mongodb.conf
        regexp: '^bind_ip\s*=\s*127\.0\.0\.1'
        replace: 'bind_ip = 0.0.0.0'

    - name: Ensure MongoDB is started and enabled
      service:
        name: mongodb
        state: started
        enabled: yes

    - name: Restart MongoDB to apply config changes
      service:
        name: mongodb
        state: restarted
